"""Add student documents table

Revision ID: 17a4e103a30c
Revises: 001_initial
Create Date: 2026-03-05 19:54:18.920825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a4e103a30c'
down_revision: Union[str, None] = 'create_all_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The student_documents table is now created in create_all_tables migration
    # This migration only handles constraint fixes
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if constraint exists before dropping (handle manually created tables)
    from sqlalchemy import text
    
    # Get connection to check constraint existence
    conn = op.get_bind()
    
    # Check if students_user_id_key exists
    result = conn.execute(text("""
        SELECT constraint_name FROM information_schema.table_constraints 
        WHERE table_name = 'students' AND constraint_name = 'students_user_id_key'
    """))
    if result.fetchone():
        op.drop_constraint(op.f('students_user_id_key'), 'students', type_='unique')
    
    # Check if users_email_key exists
    result = conn.execute(text("""
        SELECT constraint_name FROM information_schema.table_constraints 
        WHERE table_name = 'users' AND constraint_name = 'users_email_key'
    """))
    if result.fetchone():
        op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Restore unique constraints
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('students_user_id_key'), 'students', ['user_id'], postgresql_nulls_not_distinct=False)
    # Note: is_active column is now part of create_all_tables migration
    # ### end Alembic commands ###
